### ISSUE TITLE
Base64 encoding not working

### ISSUE THREAD

**Issue by krishofs** [npp-plugins/mimetools#10]
Hi

Running Win10, Notepad++ 7.6.4 x64, MIME Tools 2.5.
Base64 encoding bugged itself up today, used it yesterday with no issues.

When trying for example base64 encode this text, the output is wrong. Text is UTF8.

`This is a test www.google.com`
![image](https://user-images.githubusercontent.com/22492302/55479267-ff5f8080-561d-11e9-8b29-1853e355eeee.png)

`VGhpcyBpcyBhIHRlc3Qgd3d3Lmdvb2dsZS5jb20`
![image](https://user-images.githubusercontent.com/22492302/55479288-0b4b4280-561e-11e9-8548-a2ded12a4f31.png)

But the correct output should be:
`VGhpcyBpcyBhIHRlc3Qgd3d3Lmdvb2dsZS5jb20=`

**Comment by c0c0bird** [comment]
All padding characters are missing.

I updated from Notepadd++ 7.? with MIME Tools 2.5 to 7.7.1 yesterday. Since the update, the mime encoding leaves out padding.
Removing and re-installing all plugins did not help.

**Comment by Karthikrao121** [comment]
Is anyone fixing this issue?

**Comment by MichelLaviron** [comment]
Try using the option "Base64 Encode with padding" instead. It works fine for me, padding "=" are added as expected.

**Comment by donho** [comment]
It's a feature but not a bug.
As @MichelLaviron suggested, use the option "Base64 Encode with padding" instead if you need padding.
