### ISSUE TITLE
Feature request: XML encode/decode

### ISSUE THREAD

**Issue by Pernat1y** [npp-plugins/mimetools#12]
### Description of the Issue
This is a feature request to add options to encode/decode XML.
Something similar to existing "MIME Tools \ URL Encode" feature, but for XML :)

https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.1110
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rdipardo** [comment]
In the meantime, there's the [HTML Tag plugin](https://community.notepad-plus-plus.org/topic/22503/new-version-of-html-tag). 
It (de/en)codes XML and HTML entities, and recent versions also work with Unicode escape sequences:
<div align="center"><img width="680" src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZHd0bmgxYjNxMmNhNWhrM3pzYnBuZ2oycmpsNWZmZmNraHdsdXZwaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/TquQJuapwot1Axw3AR/giphy.gif"/>
</div>
