### ISSUE TITLE
Base64 encoding missing trailing padding character (==)

### ISSUE THREAD

**Issue by chrisemsen** [npp-plugins/mimetools#19]
The padding characters are not output when encode strings short string.

For example encoding: "ABCDE-FGHIJKLMNO" with the plug-in yields "QUJDREUtRkdISUpLTE1OTw" but with any number of online tools yields "QUJDREUtRkdISUpLTE1OTw=="

**Comment by donho** [comment]
https://stackoverflow.com/questions/4080988/why-does-base64-encoding-require-padding-if-the-input-length-is-not-divisible-by
