### ISSUE TITLE
crash when URL-encoding empty parentheses () in UTF-8

### ISSUE THREAD

**Issue by jeichberger** [npp-plugins/mimetools#25]
NPP crashes when trying to URL-encode two parentheses characters in utf-8.

Steps to reproduce:

- create or open a file
- set Encoding to UTF-8
- type empty parentheses () anywhere in the file
- select exactly these parentheses
- click on Plugins -> MIME Tools -> Full URL Encode
- NPP crashes

Environment:
- Windows 11 Enterprise, 22H2
- Notepad++ v8.5.7 (64-bit)
- Mime tools 2.9

**Comment by gerdb42** [comment]
Same issue here, though I can't reliably reproduce the crash. Occasionally, NPP crashes after using "URL Encode". Also the crash does not always happen immediately, but on a subsequent action. The following is shown in the Windows Application Log:
```
Faulting application name: notepad++.exe, version: 8.6.0.0, time stamp: 0x655f7686
Faulting module name: ntdll.dll, version: 10.0.19041.3693, time stamp: 0x3ab9e7d5
Exception code: 0xc0000374
Fault offset: 0x000e6d13
Faulting process id: 0x22a0
Faulting application start time: 0x01da2469136523af
Faulting application path: C:\Program Files (x86)\Tools\Notepad++\notepad++.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: d95a2529-6b95-4cd5-9b87-717b039715de
Faulting package full name: 
Faulting package-relative application ID: 
```
