### ISSUE TITLE
Running Base64 Decode with certain strings causes memory consumption and application to stop responding.

### ISSUE THREAD

**Issue by mak0t0san** [npp-plugins/mimetools#6]
Create a new document in Notepad++ and paste in the following string:
`lEJk24X1wEOA5CE0hPoa/g==`

Highlight the text and then right-click, and choose "Plugin commands > Base64 Decode".

Notepad++'s memory usage will quickly increase, and the program becomes unresponsive.

**Comment by donho** [comment]
@mak0t0san Thank you for your report.
I cannot reproduce on Notepad++ v7.6.2 and MimeTools v2.2.
Could you provide your Notepad++ version and MimeTools version?

**Comment by mak0t0san** [comment]
Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NPPJSONViewer.dll 

Using Mime tools 2.2 as well.

Someone else posted a similar issue in the notepad-plus-plus repository: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5042

This happens when using the UTF-8 encoding.  Using another encoding like ANSI does not cause this issue.  However, if Base64 Decode while in ANSI encoding, then switch to UTF-8, and then type in any text, it will freeze.

**UPDATE:**
Updating DSpellCheck to 1.4.9 fixed this issue.  Seems to have been a problem with the spell check plug-in that's been resolved.
