### ISSUE TITLE
Base64 encode/decode doesn't work correctly with NUL character

### ISSUE THREAD

**Issue by M-HT** [npp-plugins/mimetools#7]
Decoding the string `YQBh` should produce 3 characters (second is NUL), but it only produces 1 character.
Encoding the 3 characters produces string `YSBh` instead of `YQBh` - NUL character is replaced with space.

It works correctly in version 2.1.

**Comment by donho** [comment]
Could you provide your Notepad++ version and your MIME Tools version?

**Comment by M-HT** [comment]
I'm using Notepad++ v7.6.2 (32-bit). I tried versions 2.2 and 2.3 of MIME Tools and both didn't work, so I switched back to 2.1 which works.
